[package]
name = "wttrbar"
version = "0.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.4.7", features = ["derive"] }
pad = "0.1.6"
reqwest = { version = "0.11.16", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.96"
anyhow = "1.0"

[[bin]]
name = "wttrbar"
path = "main.rs"
